// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// entry_at
List entry_at(List input_list, std::vector<int> at);
RcppExport SEXP _rlazycartesian_entry_at(SEXP input_listSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input_list(input_listSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type at(atSEXP);
    rcpp_result_gen = Rcpp::wrap(entry_at(input_list, at));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rlazycartesian_entry_at", (DL_FUNC) &_rlazycartesian_entry_at, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rlazycartesian(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
