# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.entry_at <- function(input_list, at) {
    .Call(`_rlazycartesian_entry_at`, input_list, at)
}

